#:kivy 1.0

<Controller>:
  label_wid: my_custom_label

  BoxLayout:
    orientation: 'vertical'
    padding: 20

    Button:
      text: 'My controller info is: ' + root.info
      on_press: root.do_action()

    Label:
      id: my_custom_label
      text: 'My label before button press'

    Button:
      text: 'I have another controller info: ' + root.information
      on_press: root.do_process_information()
